
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action ToolsAction;
	
	private global::Gtk.Action HomePageAction;
	
	private global::Gtk.Action AngularMaterialWebsiteAction;
	
	private global::Gtk.Action ReloadAction;
	
	private global::Gtk.Action ResourceListAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.ToolsAction = new global::Gtk.Action ("ToolsAction", global::Mono.Unix.Catalog.GetString ("Tools"), null, null);
		this.ToolsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Tools");
		w1.Add (this.ToolsAction, null);
		this.HomePageAction = new global::Gtk.Action ("HomePageAction", global::Mono.Unix.Catalog.GetString ("Home Page"), null, null);
		this.HomePageAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Home Page");
		w1.Add (this.HomePageAction, null);
		this.AngularMaterialWebsiteAction = new global::Gtk.Action ("AngularMaterialWebsiteAction", global::Mono.Unix.Catalog.GetString ("Angular Material Website"), null, null);
		this.AngularMaterialWebsiteAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Angular Material Website");
		w1.Add (this.AngularMaterialWebsiteAction, null);
		this.ReloadAction = new global::Gtk.Action ("ReloadAction", global::Mono.Unix.Catalog.GetString ("Reload"), null, null);
		this.ReloadAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Reload");
		w1.Add (this.ReloadAction, null);
		this.ResourceListAction = new global::Gtk.Action ("ResourceListAction", global::Mono.Unix.Catalog.GetString ("Resource List"), null, null);
		this.ResourceListAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Resource List");
		w1.Add (this.ResourceListAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='ToolsAction' action='ToolsAction'><menuitem name='HomePageAction' action='HomePageAction'/><menuitem name='AngularMaterialWebsiteAction' action='AngularMaterialWebsiteAction'/><menuitem name='ReloadAction' action='ReloadAction'/><menuitem name='ResourceListAction' action='ResourceListAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.HomePageAction.Activated += new global::System.EventHandler (this.MenuActionShowHomePage);
		this.AngularMaterialWebsiteAction.Activated += new global::System.EventHandler (this.MenuActionShowAngularMaterial);
		this.ReloadAction.Activated += new global::System.EventHandler (this.MenuActionReload);
		this.ResourceListAction.Activated += new global::System.EventHandler (this.MenuActionShowResources);
	}
}
